### ISSUE TITLE
data race on field com.martiansoftware.nailgun.NGServer.shutdown

### ISSUE THREAD

**Issue by yilongli** [facebook/nailgun#64]
Two race reports on this:

```
Data race on field com.martiansoftware.nailgun.NGServer.shutdown: {{{
    Concurrent read in thread T13 (locks held: {})
 ---->  at com.martiansoftware.nailgun.NGServer.run(NGServer.java:416)
    T13 is created by T1
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:72)

    Concurrent write in thread T47 (locks held: {Monitor@77ca2286})
 ---->  at com.martiansoftware.nailgun.NGServer.shutdown(NGServer.java:320)
        - locked Monitor@77ca2286 at com.martiansoftware.nailgun.NGServer.shutdown(NGServer.java:316) 
        at org.kframework.kserver.KServerFrontEnd.nailMain(KServerFrontEnd.java:130)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
    T47 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}

Data race on field com.martiansoftware.nailgun.NGServer.shutdown: {{{
    Concurrent read in thread T13 (locks held: {})
 ---->  at com.martiansoftware.nailgun.NGServer.run(NGServer.java:426)
    T13 is created by T1
        at org.kframework.kserver.KServerFrontEnd.run(KServerFrontEnd.java:72)

    Concurrent write in thread T47 (locks held: {Monitor@77ca2286})
 ---->  at com.martiansoftware.nailgun.NGServer.shutdown(NGServer.java:320)
        - locked Monitor@77ca2286 at com.martiansoftware.nailgun.NGServer.shutdown(NGServer.java:316) 
        at org.kframework.kserver.KServerFrontEnd.nailMain(KServerFrontEnd.java:130)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
    T47 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

The spinning loop [here](https://github.com/martylamb/nailgun/blob/master/nailgun-server/src/main/java/com/martiansoftware/nailgun/NGServer.java#L416) is broken because `NGServer.shutdown` is neither volatile nor atomic variable and it's not protected by a lock. Judging from the code, you probably want `NGServer.shutdown` to be set to true exactly once. So in this case, I would say it's better to declare `shutdown` as an `AtomicBoolean`.

**Comment by jvican** [comment]
Has this ever been merged to master?

**Comment by styurin** [comment]
NGServer.shutdown is an AtomicBoolean so I believe this issue is fixed: https://github.com/facebook/nailgun/blob/e3416a6cf640493abdcb0224789adc222c3bc733/nailgun-server/src/main/java/com/martiansoftware/nailgun/NGServer.java#L64
