### ISSUE TITLE
data race on field com.martiansoftware.nailgun.NGSessionPool.done

### ISSUE THREAD

**Issue by yilongli** [facebook/nailgun#66]
Race report:

```
Data race on field com.martiansoftware.nailgun.NGSessionPool.done: {{{
    Concurrent read in thread T15 (locks held: {Monitor@2c7d1e9c})
 ---->  at com.martiansoftware.nailgun.NGSessionPool.give(NGSessionPool.java:102)
        - locked Monitor@2c7d1e9c at com.martiansoftware.nailgun.NGSessionPool.give(NGSessionPool.java:101) 
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:362)
    T15 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)

    Concurrent write in thread T47 (locks held: {})
 ---->  at com.martiansoftware.nailgun.NGSessionPool.shutdown(NGSessionPool.java:116)
        at com.martiansoftware.nailgun.NGServer.shutdown(NGServer.java:328)
        at org.kframework.kserver.KServerFrontEnd.nailMain(KServerFrontEnd.java:130)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
    T47 is created by T13
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:85)
}}}
```

Similar to #65. The assignment `done = true` at [line#116](https://github.com/martylamb/nailgun/blob/master/nailgun-server/src/main/java/com/martiansoftware/nailgun/NGSessionPool.java#L116) is not properly synchronized.

**Comment by sbalabanov** [comment]
Closing all issues older than 6 months; please reopen if it is still relevant
